'use strict'

// tests for hello
// Generated by serverless-mocha-plugin

const mod = require('../handler.js')
const mochaPlugin = require('serverless-mocha-plugin')

const lambdaWrapper = mochaPlugin.lambdaWrapper
const expect = mochaPlugin.chai.expect
const wrapped = lambdaWrapper.wrap(mod, { handler: 'hello' })

describe('hello', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done()
  })

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty
    })
  })

  it('should return the correct status code', () => {
  	return wrapped.run({}).then((response) => {
  		expect(response.statusCode).to.be.equal(200)
  	})
  })

  it('should return the correct body', () => {
  	return wrapped.run({}).then((response) => {
  		const body = JSON.parse(response.body)
  		expect(body.message).to.be.equal('Go Serverless v1.0! Your function executed successfully!')
  	})
  })
})
